### PR TITLE
Introducing an implementation of an AVL tree and a priority queue

### PR DESCRIPTION
**Pull request by vvaltchev**

### CODE REVIEW

**Comment by ZombineDev** [comment]
Very nice queue of changes you got there :P

**Comment by vvaltchev** [comment]
Thanks Petar! I spent a lot of energies to make the intrusive AVL trees to work well.
The pq was easy. You're right about using typedef struct pqueue: for pqueue_elem it is needed, for pqueue, it is not.

Do you mind making the trivial change and creating a pull request? Now that exOS has CI with builds and tests, it is simple to make a change and validate it at least partially. Also, that having a change by a contributor is so cool! :-)

**Comment by ZombineDev** [comment]
Hey Vlad, I was actually planning on doing a full review (just started from the first commit), but I am on the road with my phone and other things came in the way. I'll try tonight or later tomorrow to have a more serious look :P

**Comment by vvaltchev** [comment]
That's perfectly fine :-) Thanks Petar!

**Comment by vvaltchev** [comment]
Just one note: consider that I discarded a lot of stuff in the commits, so only the final version of the change is "reviewable" :-)
Note 2, I had not enough time to write beautiful code for the tests. Some pieces of test code are really dirty :-(

**Comment by ZombineDev** [comment]
No problem, I won't send the code to Linus just yet ;)

**Pull request merged**
